// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace Lab_2.Models;

[Table("Course")]
public partial class Course
{
    [Key]
    [Column("Crs_Id")]
    public int CrsId { get; set; }

    [Column("Crs_Name")]
    [StringLength(50)]
    public string CrsName { get; set; }

    [Column("Crs_Duration")]
    public int? CrsDuration { get; set; }

    public int DeptId { get; set; }
    public virtual Department Dept { get; set; }

    public virtual ICollection<StudentCourses> StudentCourses { get; set; }
}